### ISSUE TITLE
Global variable communication between children and container

### ISSUE THREAD

**Issue by stillwer** [NCAR/WVD-MCSupdate#107]
Currently the children all report back to the container through a global variable. This seems to be susceptible to having one state checked out in two places then checked back in causing changes from the first check in to be lost with the second check in. Consider alternatives to this communication...consider queued communications instead for example.

**Comment by BradSchoenrock** [comment]
Note: this manifests itself as the children being non responsive, when in fact they are.

**Comment by stillwer** [comment]
Turns out that queues can be called very similarly to comm ports. They can be referenced, have information stacked in them, then closed. Propose having the main program instantiate a queue that each child can fill in this manner. The main container can then check in on each child using queued string responses. One added benefit is that one can watch all the main loops: those with idle timeout processes directly and those not via the queue sizes that connect the timeout type loops to the action driven loops. If the loops grow too quickly or the reported time stamps get old, something is wrong.

**Comment by BradSchoenrock** [comment]
This could be handled by the main containers command or response queue.

**Comment by stillwer** [comment]
Seems to be working well. No detected memory leaking for the first 20 minutes of runtime yet. I will mark as closed and not any other bugs that crop up related to this initial work.

**Comment by stillwer** [comment]
One other comment to make: clicking and holding the mouse down for long periods of time haults the execution of the data queue. You can see this by probing the queue then clicking on the main panel and holding the mouse left button down. The queue will quickly grow. This manifests itself in all the children becoming "unresponsive" at all once. This is not because they are not responding but rather because their responses are not being processed. This is a problem that I have yet to find a comparable online comment for.

**Comment by stillwer** [comment]
Adding an image of the issue. Not really very easy to see but issue has not resurfaced. Just documenting (just discovered how to add pictures to github). 

![bug_childrennotresponding](https://user-images.githubusercontent.com/32913509/42097990-d66316ba-7b76-11e8-9322-c7b374dfc9aa.png)
