### ISSUE TITLE
Post Processing code adaptation

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#115]
Scott's and Matt's post processing code will need to be adapted to read NetCDF files. From there we can use that software to grab images and post them to the field catalog.

**Comment by stillwer** [comment]
Done for child netcdf files on 20180326.

**Comment by stillwer** [comment]
Running on eldora as of yesterday. The DIAL01 files have been accepted for the field catalog. DIAL02 files are still pending. All that is needed is to get the function running automatically.

**Comment by stillwer** [comment]
DIAL02 files now being accepted to field catalog as of yesterday. Cron processing of quicklook figures running as of this morning.
