### ISSUE TITLE
AdvVis - calculation flipped

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#122]
Some of the histograms coming out on AdvVis suggest the calculations are not being correctly done. Robert and I will have to sit down and look at them in more detail.

**Comment by stillwer** [comment]
Turns out the function updating the ring buffers was holding values that seemed to not be unique to each channel. So...calculation not flipped....ring buffers fixed but this fix causes new problem with instantiation of the ring buffers for each unique channel.
