### ISSUE TITLE
Power monitoring visualization not updating properly

### ISSUE THREAD

**Issue by stillwer** [NCAR/WVD-MCSupdate#135]
Today I watched the power monitoring update. It seems to be updating with 4 measurements every 2 seconds. All 4 seem to be the same but it is thus scrolling 4 times faster than measurements should be reported.

**Comment by BradSchoenrock** [comment]
This issue is because the power is being reported by each channel, so when all 4 channels return nearly simultaneously the power reports 4 times in very quick succession.

**Comment by BradSchoenrock** [comment]
marking wontfix and closing based on the fact that it is a low impact visualization bug that is hard to notice in the first place.
