### ISSUE TITLE
NetCDF - power files not being made

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#142]
There is an indexing error with the power files, most likely due to the fact that the precision of the timestamps was increased.

**Comment by BradSchoenrock** [comment]
indexing error fixed on DIAL1

DIAL2 is still running old version of software, i fixed how it runs because it had a hodgepodge of old and new software relating to how power monitoring was being handled causing merged files to not have power info. In git speak i detached its operations from head, so it is now running on a separate branch. Changes to the master branch will not be able to be pulled onto that machine until its wavemeter is updated to reflect how DIAL1 operates. 

This might create a situation where we want to support two different types of hardware. WM_Ethernet and WM_Serial or something to that effect.

**Comment by stillwer** [comment]
This isn't so much a bug as a limit on space. I made the screen as small as possible to fit the operational window. Without the menubar, the screen is shorter and can be moved up to gain more screen real estate. When the program stops, the menu bar returns and the screen gets taller. If this is really a problem, the screen just needs to be moved down programmatically. This can be done by copying the code that moves it from the configure look. I can do it if this is annoying.
