### ISSUE TITLE
Computer BIOS to be Natively On

### ISSUE THREAD

**Issue by stillwer** [NCAR/WVD-MCSupdate#178]
Need to set the computer startup procedure on power down to be natively on. I believe this can be done via the BIOS settings. Scott mentioned doing it in the past and that would allow for restart after a power blip.

**Comment by BradSchoenrock** [comment]
related to #114

**Comment by stillwer** [comment]
Done on DIAL1 last week.

**Comment by stillwer** [comment]
This has been added to the install list and can be done when setting up the micro form factor computers in the future.
