### ISSUE TITLE
RSync pulling from wrong place

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#180]
I think the RSync is pulling from the desktop instead of from the WVD directory. The desktop is temporarily being used as a placeholder for an external hard drive which is meant to provide a redundant copy of the data. This means that when the files get RSynced to eldora they all have timestamps reflecting the fact that files were changed every time it tries to pull instead of when files are actually created. When we update the software for Relampago we need to set up an external hard drive and change where RSync is getting things from.

**Comment by stillwer** [comment]
Fixed on DIAL 2 Monday. Easy to do....now pointing directly at the data file directory.

**Comment by BradSchoenrock** [comment]
Eldora is complaining about the change, 

@ERROR: Unknown module 'wvdial'

Did you change the name of the RSync server when you moved it?

**Comment by BradSchoenrock** [comment]
This was fixed, re-closing the issue.
