### ISSUE TITLE
RSync taking too long and not transfering data

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#188]
When the RSync takes too long another instance will begin and when that happens things get weird. 

Example taken from - 

/export/eldora2/rsfdata/logs/errors/20180618/rsync_dial_data_from_field_Data.dial1.cron.log 

21:21:26 - running cmd: rsync -avz --compress-level=9 "rsync://166.164.215.174/wvdial1/NetCDFOutput/20180618*" .
21:21:26 - receiving incremental file list
21:21:35 - 20180618/
21:21:41 - 20180618/Etalonsample190000.nc
21:21:41 - 20180618/Etalonsample200000.nc
21:21:41 - 20180618/Etalonsample210000.nc
21:21:41 - 20180618/HKeepsample190000.nc
21:21:41 - 20180618/HKeepsample200000.nc
21:21:41 - 20180618/HKeepsample210000.nc
21:21:41 - 20180618/LLsample190000.nc
21:21:41 - 20180618/LLsample200000.nc
21:21:41 - 20180618/LLsample210000.nc
21:21:48 - 20180618/MCSsample190000.nc
21:21:49 - 20180618/MCSsample200000.nc
21:26:17 - 20180618/MCSsample210000.nc
21:31:38 - Running:  rsync_dial_data_from_field.py

It looks like RSync ing the 20 file took several minutes, and the 21 file was running when the script was called again. The 21 file is not currently on eldora because it is getting interrupted and is sending us errors. 

EDIT: file path changed from "today" which is a changing symbolic link to the actual date.

**Comment by BradSchoenrock** [comment]
This is coupled with the problem that too many connections are being opened so it stops trying. - 

 running cmd: rsync -avz --compress-level=9 "rsync://166.164.215.174/wvdial1/NetCDFOutput/20180616*" .
21:31:55 - @ERROR: max connections (2) reached -- try again later
21:31:55 - rsync error: error starting client-server protocol (code 5) at main.c(1516) [Receiver=3.0.9]
21:31:55 - Child returned code:  5

**Comment by BradSchoenrock** [comment]
Once we get later on in the hour then the 20 hour file seemed to go right by and it is taking longer to transfer the 21 file 

21:51:28 - 20180618/MCSsample190000.nc
21:51:28 - 20180618/MCSsample200000.nc
21:51:29 - 20180618/MCSsample210000.nc

so it eventually is transfering, but nearly an hour late. The 21 file still isn't on eldora yet so it looks like we are still falling behind.

**Comment by stillwer** [comment]
This seems to have been fixed by allowing the IP address of the MPD02 computer to be dynamically allocated instead of forcing a particular address.
