### ISSUE TITLE
Advanced Visualization: Water vapor plot 

### ISSUE THREAD

**Issue by stillwer** [NCAR/WVD-MCSupdate#194]
The plot of the water vapor mixing ratio seems weird. There is almost a checkerboard pattern that should not exist. Its general lack of smoothness is concerning because the quicklook plots on the field catalog do not share the same character. 

![screen shot 2018-06-29 at 8 23 54 am 2](https://user-images.githubusercontent.com/32913509/42097771-3367db08-7b76-11e8-83f6-437742adbcf7.png)

**Comment by BradSchoenrock** [comment]
I have added smoothing to the WV display and the aerosol display, but the WV field still doesn't match the field catalog. There is clearly something wrong with the calculation but after looking it over several times i can't spot it. It might be worthwhile to get robert's help for this to ensure i am doing the calculations properly.
