### ISSUE TITLE
MCS range per channel

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#196]
In the future we want the ability to set ranges for each channel on the MCS independently. HSRL, WVOnline, etc... can in principle all be on their own ranges with seperate bin sizes. 

This would require significant hardware changes to the MCS by Josh to support and significant changes to software for MCS(Raw returns), MCS controls, advanced visualization, and merging at minimum. Changes to laser timing would also be necessary.

**Comment by BradSchoenrock** [comment]
Related to #190

**Comment by stillwer** [comment]
The new MCS program has the ability to set range resolution for each channel individually. It currently forces all channels to be the same (and takes the zeroth channel as the reference for now) but that can easily be taken out of the program should the hardware ever support this functionality.
