### ISSUE TITLE
Advanced Vis - HSRL Data plotting on DIAL 3

### ISSUE THREAD

**Issue by stillwer** [NCAR/WVD-MCSupdate#204]
I am noticing that there is aerosol backscatter coefficient being plotted and calculated for DIAL 3. It is problematic to me because it shouldn't exist at all as there is no HSRL laser on that system. More generally, I think we should find a way to only plot that which we have the capability to measure in advanced vis and be able to turn off features that are not being used programatically.

**Comment by stillwer** [comment]
Here is a photo of what I see. 
<img width="1248" alt="screen shot 2018-07-19 at 10 41 42 pm" src="https://user-images.githubusercontent.com/32913509/42983622-f3f996b6-8ba4-11e8-892c-a6b610332301.png">

**Comment by stillwer** [comment]
I see the same thing on DIAL 2 with no HSRL laser. 
<img width="1383" alt="screen shot 2018-07-19 at 10 47 23 pm" src="https://user-images.githubusercontent.com/32913509/42983783-c7484634-8ba5-11e8-849f-02c04c1aae4e.png">

**Comment by BradSchoenrock** [comment]
Interesting. Yesterday in my discussion with Scott he seemed to suggest that HSRL is not needed to calculate Aerosol Backscatter, and asked me to look into why the plots have no structure and don't match the Relative Backscatter plot from the field catalog. Are Relative Backscatter and Aerosol Backscatter the same thing? When i asked Scott that question yesterday he said they were the same, so i'm confused by what the two of you want to see here and how those fields should be calculated.

**Comment by stillwer** [comment]
I am going to close this issue and reopen in a more descriptive task. I would like to tear apart the Advanced visualization to only show plots of features that are connected. This task will fall under that list.
