### ISSUE TITLE
automatic online wavelength control based on optical depth

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#22]
On 9/1 Scott Spuler asked 

> 5.) automatic online wavelength control based on optical depth (slave offline and etalon temp)

Could you go into more depth on this change? I think this is pretty doable on the software side but again i'll have to speak with Josh a bit to get the details ironed out. 

> We need to work out how best to do this first before we think about a Labview implementation.  I'll work with Matt Hayman on this and get back to you.

Still waiting for outcome of any discussions at this time. Marked wontfix until actionable follow up. 

Brad Schoenrock

**Comment by BradSchoenrock** [comment]
Still on hold but was mentioned in meeting, so reopening.

**Comment by stillwer** [comment]
Added a different issue to do this control. Automatic control is not a good idea in my opinion.
