### ISSUE TITLE
Add Child: Power switches

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#54]
This will require advanced user permissions to operate.

**Comment by stillwer** [comment]
We want to be able to control the power switches, which are now controlled via a webpage based system, as a labview child. This preferable is a permission sensitive item that would allow you to toggle the power on any hardware you wanted to from labview. This would run as a single control like MCS or Weather station but not as an operational child.

**Comment by BradSchoenrock** [comment]
Finished this morning and tested. Seemed to work just fine. ~Robert
