### ISSUE TITLE
Add Child: Environment housekeeping (thermocouples)

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#55]
This will likely be a simpler task equivalent in scope to implementing the weather station.

**Comment by stillwer** [comment]
Done and writing data on DIAL 1. Note that there is two small bugs...I need to hook up the number of thermocouples to read in the communication program. It is defaulting to 3 right now, which is what Scott had as default. Additionally, the conversion from thermocouple hardware to temperature is currently wrong. Both should be small fixes.

**Comment by stillwer** [comment]
Fixed bug this morning with the thermocouple temperature. The hardware is a T type thermocouple (temperature limits from -100 to 400 C) but the hardware thought it was a K type (temperature limits from 0 to 1370 C).
