### ISSUE TITLE
Container - Add alignment configuration patterns

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#62]
This is similar to child testing routines #59 but for operational calibrations and desired patterns.

**Comment by stillwer** [comment]
Underway. I did the wavemeter a few days ago and will try to do the 2 x 1 switches soon. No advanced alignment scans have been made but the building blocks are there.

**Comment by stillwer** [comment]
Going to mark this as resolved and add more specific alignment scan comments that are single tasks.
