### ISSUE TITLE
MCS - set IP address

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#98]
A bit before holiday break Josh was looking into setting the IP address of the MCS and setting the IP address of the computer that the MCS is talking to. I will have to follow up on how successful he was in that, and implement that as control into the MCS child.

**Comment by stillwer** [comment]
This is just lingering and not set for fixing. I am going to close this and if we have more specific MCS updates...will add them later. For now...no planned change to make the MCS's IP address settable via software is planned.
